### ISSUE TITLE
Fix TaskProgressBar

### ISSUE THREAD

**Issue by XavierNovoa** [dani17b/lib-productivio#25]
Fix TaskProgressBAr to properly visualize it on storybook

**Comment by Br1lopez** [comment]
A mi me fue sin problema despues de hacer yarn install

**Comment by XavierNovoa** [comment]
> 

voy a probar si funciona, sino hago la pr con el cambio

**Comment by XavierNovoa** [comment]
> A mi me fue sin problema despues de hacer yarn install

voy a probar, si no funciona hago la pr

**Comment by XavierNovoa** [comment]
Sigue dando el siguiente error:

![image](https://user-images.githubusercontent.com/116115551/225884339-a95d4f97-d02f-44e0-a5d9-376b83ec31b4.png)
